package king.rapper.pgone.pgonediary.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import king.rapper.pgone.pgonediary.entity.NoteRecording;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE_RECORDING".
*/
public class NoteRecordingDao extends AbstractDao<NoteRecording, Long> {

    public static final String TABLENAME = "NOTE_RECORDING";

    /**
     * Properties of entity NoteRecording.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NoteRecordingId = new Property(0, Long.class, "noteRecordingId", true, "_id");
        public final static Property NoteJoinRecordingId = new Property(1, Long.class, "noteJoinRecordingId", false, "NOTE_JOIN_RECORDING_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property FilePath = new Property(3, String.class, "filePath", false, "FILE_PATH");
        public final static Property Length = new Property(4, Long.class, "length", false, "LENGTH");
        public final static Property Time = new Property(5, Long.class, "time", false, "TIME");
    }

    private Query<NoteRecording> noteInfo_RecordingListQuery;

    public NoteRecordingDao(DaoConfig config) {
        super(config);
    }
    
    public NoteRecordingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE_RECORDING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: noteRecordingId
                "\"NOTE_JOIN_RECORDING_ID\" INTEGER," + // 1: noteJoinRecordingId
                "\"NAME\" TEXT," + // 2: name
                "\"FILE_PATH\" TEXT," + // 3: filePath
                "\"LENGTH\" INTEGER," + // 4: length
                "\"TIME\" INTEGER);"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE_RECORDING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NoteRecording entity) {
        stmt.clearBindings();
 
        Long noteRecordingId = entity.getNoteRecordingId();
        if (noteRecordingId != null) {
            stmt.bindLong(1, noteRecordingId);
        }
 
        Long noteJoinRecordingId = entity.getNoteJoinRecordingId();
        if (noteJoinRecordingId != null) {
            stmt.bindLong(2, noteJoinRecordingId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
 
        Long length = entity.getLength();
        if (length != null) {
            stmt.bindLong(5, length);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NoteRecording entity) {
        stmt.clearBindings();
 
        Long noteRecordingId = entity.getNoteRecordingId();
        if (noteRecordingId != null) {
            stmt.bindLong(1, noteRecordingId);
        }
 
        Long noteJoinRecordingId = entity.getNoteJoinRecordingId();
        if (noteJoinRecordingId != null) {
            stmt.bindLong(2, noteJoinRecordingId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
 
        Long length = entity.getLength();
        if (length != null) {
            stmt.bindLong(5, length);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NoteRecording readEntity(Cursor cursor, int offset) {
        NoteRecording entity = new NoteRecording( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // noteRecordingId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // noteJoinRecordingId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // filePath
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // length
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NoteRecording entity, int offset) {
        entity.setNoteRecordingId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNoteJoinRecordingId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFilePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLength(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NoteRecording entity, long rowId) {
        entity.setNoteRecordingId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NoteRecording entity) {
        if(entity != null) {
            return entity.getNoteRecordingId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NoteRecording entity) {
        return entity.getNoteRecordingId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "recordingList" to-many relationship of NoteInfo. */
    public List<NoteRecording> _queryNoteInfo_RecordingList(Long noteJoinRecordingId) {
        synchronized (this) {
            if (noteInfo_RecordingListQuery == null) {
                QueryBuilder<NoteRecording> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.NoteJoinRecordingId.eq(null));
                noteInfo_RecordingListQuery = queryBuilder.build();
            }
        }
        Query<NoteRecording> query = noteInfo_RecordingListQuery.forCurrentThread();
        query.setParameter(0, noteJoinRecordingId);
        return query.list();
    }

}
