package king.rapper.pgone.pgonediary.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import king.rapper.pgone.pgonediary.entity.WeatherIcon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEATHER_ICON".
*/
public class WeatherIconDao extends AbstractDao<WeatherIcon, Long> {

    public static final String TABLENAME = "WEATHER_ICON";

    /**
     * Properties of entity WeatherIcon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property WeatherIconId = new Property(0, Long.class, "weatherIconId", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property Time = new Property(3, Long.class, "time", false, "TIME");
    }


    public WeatherIconDao(DaoConfig config) {
        super(config);
    }
    
    public WeatherIconDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEATHER_ICON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: weatherIconId
                "\"URL\" TEXT," + // 1: url
                "\"TYPE\" TEXT," + // 2: type
                "\"TIME\" INTEGER);"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEATHER_ICON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WeatherIcon entity) {
        stmt.clearBindings();
 
        Long weatherIconId = entity.getWeatherIconId();
        if (weatherIconId != null) {
            stmt.bindLong(1, weatherIconId);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WeatherIcon entity) {
        stmt.clearBindings();
 
        Long weatherIconId = entity.getWeatherIconId();
        if (weatherIconId != null) {
            stmt.bindLong(1, weatherIconId);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WeatherIcon readEntity(Cursor cursor, int offset) {
        WeatherIcon entity = new WeatherIcon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // weatherIconId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WeatherIcon entity, int offset) {
        entity.setWeatherIconId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WeatherIcon entity, long rowId) {
        entity.setWeatherIconId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WeatherIcon entity) {
        if(entity != null) {
            return entity.getWeatherIconId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WeatherIcon entity) {
        return entity.getWeatherIconId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
